<a href="https://colab.research.google.com/github/AvishekRoy16/DeepLearning/blob/master/6-Pytorch/Pytorch-Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Outline
* PyTorch
* What are tensors
* Initialising, slicing, reshaping tensors
* Numpy and PyTorch interfacing
* GPU support for PyTorch + Enabling GPUs on Google Colab
* Speed comparisons, Numpy -- PyTorch -- PyTorch on GPU
* Autodiff concepts and application
* Writing a basic learning loop using autograd
* Exercises

In [73]:
import torch
import numpy as np
import matplotlib.pyplot as plt

Tensor is a kind of datastructure just like vector and matrics (list and dataframed/2D Lists).  
They have a higher order and also many tensors have relation between them.

## Initialise Tensors

In [74]:
# Makes the tensors of the specified dimentions and fill them with ones
x = torch.ones(3,2)
print(x)

# Makes the tensors of the specified dimentions and fill them with zeros
x = torch.zeros(3, 2)
print(x)

# Makes the tensors of the specified dimentions and fill them with random numbers
x = torch.rand(3, 2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.9788, 0.2605],
        [0.8890, 0.1032],
        [0.2772, 0.7433]])


In [75]:
# Will create space for the dimentions spesified but will not initialise value in it
x = torch.empty(3, 2)
print(x)

# if we want to give something the same shape as another tensor we can do that
y = torch.zeros_like(x)
print(y)

tensor([[6.5650e+28, 1.7788e+25],
        [1.3425e+13, 1.1168e+33],
        [2.5348e-09, 1.0765e+21]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [76]:
# Create a linearspace start, end, steps - start and end are included
x = torch.linspace(0, 1, steps=5)
print(x)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [77]:
# Manually defining the tensors
x = torch.tensor([[1, 2], 
                 [3, 4], 
                 [5, 6]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


## Slicing tensors

In [78]:
# Dimentions of the tensors are fiven insde a list
print(x.size())

# slicing[rows: column]
# Take all rows and print the column of id 1
print(x[:, 1]) 
# Take the 0th roaw and print all the column in that
print(x[0, :])

# All the rules for slicing in list apply to tensors as well

torch.Size([3, 2])
tensor([2, 4, 6])
tensor([1, 2])


In [79]:
# We are accessing a particular element from the x rows we are accessing the element in the 
# first row and first column, The data type of the element still remains tensor
y = x[1, 1]
print(y)
# To change the data type of the element while accessing it from tensor to it's actual datatype.
print(y.item())

tensor(4)
4


## Reshaping tensors

Dimentions play a very important role in machine learning and we have to keep track of what we are multiplying with what when we are trying to do matrix multiplications and other operation that erquire the dimentions of the tensors to be correct

In [80]:
# To view the tensor in another dimentions we can use views - views(row, column)
print(x)
y = x.view(2, 3)
print(y)

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [81]:
# We can reshape it when we know pnly one of the dimentions and 
# it will pick and appropriate number to put in the second dimention, to do that we have to fill -1 in
# the dimention we do not know the number
y = x.view(6,-1) 
print(y)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


## Simple Tensor Operations

In [82]:
# Simple operations in Tesors
x = torch.ones([3, 2])
y = torch.ones([3, 2])
z = x + y
print(z)
z = x - y
print(z)
z = x * y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [83]:
# z is being updated by adding x to y. Here y reamins the same and is not updated
z = y.add(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [84]:
# Addition in place
# We are taking y and then adding x to it and updating y in the process
z = y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


## Numpy <> PyTorch

In [85]:
# Interfacing Numpy and Pytorch

# Converted tensor into numpy
x_np = x.numpy()
print(type(x), type(x_np))
print(x_np)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [86]:
# Converting a numpy array into a tenors
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(type(a), type(a_pt))
print(a_pt)
# This is less of copying and more a bridge between the two as if we make changes into numpy,
# it will be reflected in tensor

[ 0.40097206 -0.37719441 -0.30400602  0.85176317 -2.5799248 ]
<class 'numpy.ndarray'> <class 'torch.Tensor'>
tensor([ 0.4010, -0.3772, -0.3040,  0.8518, -2.5799], dtype=torch.float64)


In [87]:
np.add(a, 1, out=a)
print(a)
print(a_pt) 

[ 1.40097206  0.62280559  0.69599398  1.85176317 -1.5799248 ]
tensor([ 1.4010,  0.6228,  0.6960,  1.8518, -1.5799], dtype=torch.float64)


In [88]:
%%time
# Checking the time taken to loop and add random numbers using numpy arrays
for i in range(100):
  a = np.random.randn(100,100) # (100,100) is the matrix size
  b = np.random.randn(100,100)
  c = np.matmul(a, b)

Wall time: 429 ms


In [89]:
%%time
# Checking the time taken to loop and add random numbers using tensors
for i in range(100):
  a = torch.randn([100, 100])
  b = torch.randn([100, 100])
  c = torch.matmul(a, b)

# Note we are still not using the GPU.

Wall time: 501 ms


In [90]:
%%time
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  c = a + b

Wall time: 1min 19s


In [91]:
%%time
for i in range(10):
  a = torch.randn([10000, 10000])
  b = torch.randn([10000, 10000])
  c = a + b

Wall time: 23 s


## CUDA support

In [92]:
print(torch.cuda.device_count())

1


In [93]:
print(torch.cuda.device(0))
print(torch.cuda.get_device_name(0))

NVIDIA GeForce MX150


In [94]:
cuda0 = torch.device('cuda:0')

In [95]:
a = torch.ones(3, 2, device=cuda0)
b = torch.ones(3, 2, device=cuda0)
c = a + b
print(c)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')


In [96]:
print(a)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')


In [97]:
%%time
# Time comparison between numpy, cpu and gpu performance for matrix addition
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  np.add(b, a)

Wall time: 1min 17s


In [98]:
%%time
for i in range(10):
  a_cpu = torch.randn([10000, 10000])
  b_cpu = torch.randn([10000, 10000])
  b_cpu.add_(a_cpu)

Wall time: 21.8 s


In [99]:
%%time
for i in range(10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  b.add_(a)

Wall time: 2.66 s


In [100]:
%%time
# Time comparison between numpy, cpu and gpu performance for matrix multiplication
for i in range(10):
  a = np.random.randn(10000,10000)
  b = np.random.randn(10000,10000)
  np.matmul(b, a)

Wall time: 7min 14s


In [101]:
%%time
for i in range(10):
  a_cpu = torch.randn([10000, 10000])
  b_cpu = torch.randn([10000, 10000])
  torch.matmul(a_cpu, b_cpu)

Wall time: 3min 11s


In [102]:
%%time
for i in range(10):
  a = torch.randn([10000, 10000], device=cuda0)
  b = torch.randn([10000, 10000], device=cuda0)
  torch.matmul(a, b)

Wall time: 14.7 s
